## Homework 7: Linear Algebra 03

In [1]:
import numpy as np

In [7]:
#Matrix
S = np.array([[1,-1,-1,-1],
             [-1, 2, 0, 0],
             [-1, 3, 3, 0],
             [-1, 0, 1, 4]])

#Eigenvector and eigenvalues
evals , evect = np.linalg.eig(S)
print(evals, "\n", evect)

[4.86619826 0.34455762 1.78924412 3.        ] 
 [[-3.49561271e-01  7.94033408e-01  7.62229110e-02  7.67415610e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  6.86635020e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]


Calculate $S^5$ using two methods. in a "for" loop and using diagonalization. Compare the results.

In [8]:
#Using Diagonalization
P = evect
Pinv = np.linalg.inv(P)
D_5 = np.zeros((4,4))

for i in range(4):
    D_5[i,i] = evals[i]**100

S_5 = np.matmul(np.matmul(P, D_5), Pinv)
print(" S^5 using diagonalization : \n {}".format(S_5))

 S^5 using diagonalization : 
 [[ 9.34300113e+67 -1.45494637e+68 -1.07862155e+68 -1.07862155e+68]
 [-3.25971907e+67  5.07622376e+67  3.76324822e+67  3.76324822e+67]
 [-1.02465846e+68  1.59565763e+68  1.18293756e+68  1.18293756e+68]
 [-2.26155911e+68  3.52183113e+68  2.61090238e+68  2.61090238e+68]]


In [15]:
# Loop

A = np.copy(S).astype('float64')


for i in range(1,100):
    A = np.matmul(S, A)
      
print("S^5 using a loop : \n {}".format(A))

S^5 using a loop : 
 [[ 9.34300113e+67 -1.45494637e+68 -1.07862155e+68 -1.07862155e+68]
 [-3.25971907e+67  5.07622376e+67  3.76324822e+67  3.76324822e+67]
 [-1.02465846e+68  1.59565763e+68  1.18293756e+68  1.18293756e+68]
 [-2.26155911e+68  3.52183113e+68  2.61090238e+68  2.61090238e+68]]


We get the same result with both methods. 

# Michal:

* why the resultados are different if the power 100? :)
* which result do you trust?
* try: A = np.copy(S).astype('float64')